title: Cody's Dev Blog
description: Personal dev blog sharing lessons from projects and experiments.
baseurl: "/codys-dev-blog"
url: "https://codyliska.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
highlighter: rouge
